import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CookieStandHeader from '../components/Header'
import CookieStandForm from '../components/Main'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  

      <CookieStandHeader/>
      
      <CookieStandForm />
      <p>Report Table comming soon .....</p>
      <Footer/>
    </div>
  )
}
